# Generated by Django 3.2.6 on 2022-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinquiry',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
