# Generated by Django 3.2.3 on 2022-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpverifywithtimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.EmailField(blank=True, max_length=254, null=True)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
