# Generated by Django 3.2.6 on 2022-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_addbatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('batchtime', models.CharField(blank=True, max_length=255, null=True)),
                ('studentattemt', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=20, null=True)),
                ('lastupdatedon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
