# Generated by Django 3.2.6 on 2022-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_rename_screan_courses_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollmentlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('orderid', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentid', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=20, null=True)),
                ('lastupdatedon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
