# Generated by Django 3.2.6 on 2022-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_enrollmentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentlist',
            name='lastupdatedon',
        ),
        migrations.RemoveField(
            model_name='enrollmentlist',
            name='updatedby',
        ),
        migrations.AddField(
            model_name='enrollmentlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentlist',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
