# Generated by Django 3.2.6 on 2022-06-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20220611_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
