# Generated by Django 3.2.6 on 2022-06-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20220612_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollmentlist',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='created',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='updated',
        ),
    ]
